# List Comprehensions Lab

Complete the following set of exercises to solidify your knowledge of list comprehensions.

In [49]:
import os
import numpy as np
import pandas as pd

### 1. Use a list comprehension to create and print a list of consecutive integers starting with 1 and ending with 50.

In [50]:
integers_upto50 = [e+1 for e in range(50)]
print(integers_upto50)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50]


### 2. Use a list comprehension to create and print a list of even numbers starting with 2 and ending with 200.

In [51]:
evennumbers_upto200 = [e+2 for e in range(200) if e %2 == 0]
print(evennumbers_upto200)

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128, 130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154, 156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180, 182, 184, 186, 188, 190, 192, 194, 196, 198, 200]


### 3. Use a list comprehension to create and print a list containing all elements of the 10 x 4 Numpy array below.

In [52]:
a = np.array([[0.84062117, 0.48006452, 0.7876326 , 0.77109654],
       [0.44409793, 0.09014516, 0.81835917, 0.87645456],
       [0.7066597 , 0.09610873, 0.41247947, 0.57433389],
       [0.29960807, 0.42315023, 0.34452557, 0.4751035 ],
       [0.17003563, 0.46843998, 0.92796258, 0.69814654],
       [0.41290051, 0.19561071, 0.16284783, 0.97016248],
       [0.71725408, 0.87702738, 0.31244595, 0.76615487],
       [0.20754036, 0.57871812, 0.07214068, 0.40356048],
       [0.12149553, 0.53222417, 0.9976855 , 0.12536346],
       [0.80930099, 0.50962849, 0.94555126, 0.33364763]])

In [53]:
print(a)
len(a)

[[0.84062117 0.48006452 0.7876326  0.77109654]
 [0.44409793 0.09014516 0.81835917 0.87645456]
 [0.7066597  0.09610873 0.41247947 0.57433389]
 [0.29960807 0.42315023 0.34452557 0.4751035 ]
 [0.17003563 0.46843998 0.92796258 0.69814654]
 [0.41290051 0.19561071 0.16284783 0.97016248]
 [0.71725408 0.87702738 0.31244595 0.76615487]
 [0.20754036 0.57871812 0.07214068 0.40356048]
 [0.12149553 0.53222417 0.9976855  0.12536346]
 [0.80930099 0.50962849 0.94555126 0.33364763]]


10

In [54]:
a2 = [a[i][j] for i in range(len(a)) for j in range(4)]
print(a2)

[0.84062117, 0.48006452, 0.7876326, 0.77109654, 0.44409793, 0.09014516, 0.81835917, 0.87645456, 0.7066597, 0.09610873, 0.41247947, 0.57433389, 0.29960807, 0.42315023, 0.34452557, 0.4751035, 0.17003563, 0.46843998, 0.92796258, 0.69814654, 0.41290051, 0.19561071, 0.16284783, 0.97016248, 0.71725408, 0.87702738, 0.31244595, 0.76615487, 0.20754036, 0.57871812, 0.07214068, 0.40356048, 0.12149553, 0.53222417, 0.9976855, 0.12536346, 0.80930099, 0.50962849, 0.94555126, 0.33364763]


### 4. Add a condition to the list comprehension above so that only values greater than or equal to 0.5 are printed.

In [55]:
a3 = [a[i][j] for i in range(len(a)) for j in range(4) if a[i][j] >= 0.5]
print(a3)

[0.84062117, 0.7876326, 0.77109654, 0.81835917, 0.87645456, 0.7066597, 0.57433389, 0.92796258, 0.69814654, 0.97016248, 0.71725408, 0.87702738, 0.76615487, 0.57871812, 0.53222417, 0.9976855, 0.80930099, 0.50962849, 0.94555126]


### 5. Use a list comprehension to create and print a list containing all elements of the 5 x 2 x 3 Numpy array below.

In [56]:
b = np.array([[[0.55867166, 0.06210792, 0.08147297],
        [0.82579068, 0.91512478, 0.06833034]],

       [[0.05440634, 0.65857693, 0.30296619],
        [0.06769833, 0.96031863, 0.51293743]],

       [[0.09143215, 0.71893382, 0.45850679],
        [0.58256464, 0.59005654, 0.56266457]],

       [[0.71600294, 0.87392666, 0.11434044],
        [0.8694668 , 0.65669313, 0.10708681]],

       [[0.07529684, 0.46470767, 0.47984544],
        [0.65368638, 0.14901286, 0.23760688]]])

In [59]:
b2 = [b[i][j][k] for i in range(len(b)) for j in range(2) for k in range(3)]
print(b2)

[0.55867166, 0.06210792, 0.08147297, 0.82579068, 0.91512478, 0.06833034, 0.05440634, 0.65857693, 0.30296619, 0.06769833, 0.96031863, 0.51293743, 0.09143215, 0.71893382, 0.45850679, 0.58256464, 0.59005654, 0.56266457, 0.71600294, 0.87392666, 0.11434044, 0.8694668, 0.65669313, 0.10708681, 0.07529684, 0.46470767, 0.47984544, 0.65368638, 0.14901286, 0.23760688]


### 5. Add a condition to the list comprehension above so that the last value in each subarray is printed, but only if it is less than or equal to 0.5.

In [61]:
b3 = [b2[i] for i, j in enumerate(b2) if i % 3 == 0 and b2[i] >= 0.5]
print(b3)

[0.55867166, 0.82579068, 0.58256464, 0.71600294, 0.8694668, 0.65368638]


### 6. Use a list comprehension to select and print the names of all CSV files in the */data* directory.

In [62]:
entries = os.listdir('/content/Labbb')
print(entries)

['sample_file_6.csv', 'sample_file_1.csv', 'sample_file_7.csv', 'sample_file_4.txt', 'sample_file_0.txt', 'sample_file_8.txt', 'sample_file_8.csv', 'sample_file_9.csv', 'sample_file_1.txt', 'sample_file_6.txt', 'sample_file_4.csv', 'sample_file_5.txt', 'sample_file_3.csv', 'sample_file_3.txt', 'sample_file_9.txt', 'sample_file_2.csv', 'sample_file_7.txt', 'sample_file_2.txt', 'sample_file_0.csv', 'sample_file_5.csv']


In [64]:
csv_files = [f_name for f_name in os.listdir('/content/Labbb') if f_name.endswith('.csv')]
print(csv_files)

['sample_file_6.csv', 'sample_file_1.csv', 'sample_file_7.csv', 'sample_file_8.csv', 'sample_file_9.csv', 'sample_file_4.csv', 'sample_file_3.csv', 'sample_file_2.csv', 'sample_file_0.csv', 'sample_file_5.csv']


### 7. Use a list comprehension and the Pandas `read_csv` and `concat` methods to read all CSV files in the */data* directory and combine them into a single data frame. Display the top 10 rows of the resulting data frame.

In [86]:
df = pd.read_csv('/content/Labbb/sample_file_0.csv')
print(df)

          0         1         2  ...        17        18        19
0  0.734751  0.195362  0.734309  ...  0.293260  0.937828  0.880858
1  0.772607  0.445391  0.249642  ...  0.389789  0.016787  0.503695
2  0.226428  0.268764  0.694262  ...  0.334802  0.517694  0.646110
3  0.362748  0.495430  0.113876  ...  0.141746  0.771144  0.489660
4  0.033415  0.340433  0.464971  ...  0.676051  0.109349  0.872947

[5 rows x 20 columns]


In [88]:
aux =[]

for i in csv_files:
  aux.append('/content/Labbb/'+i)
print(aux)



['/content/Labbb/sample_file_6.csv', '/content/Labbb/sample_file_1.csv', '/content/Labbb/sample_file_7.csv', '/content/Labbb/sample_file_8.csv', '/content/Labbb/sample_file_9.csv', '/content/Labbb/sample_file_4.csv', '/content/Labbb/sample_file_3.csv', '/content/Labbb/sample_file_2.csv', '/content/Labbb/sample_file_0.csv', '/content/Labbb/sample_file_5.csv']


In [92]:
combined_csv = pd.concat([pd.read_csv(f) for f in aux])
print(combined_csv.head(10))

          0         1         2  ...        17        18        19
0  0.702566  0.092336  0.245083  ...  0.886644  0.472826  0.551858
1  0.177005  0.649551  0.467321  ...  0.773155  0.485385  0.686294
2  0.689556  0.445586  0.005691  ...  0.302786  0.051382  0.203699
3  0.047188  0.854596  0.833368  ...  0.183948  0.372739  0.739383
4  0.936065  0.725831  0.184239  ...  0.538712  0.885516  0.667051
0  0.276827  0.260054  0.942397  ...  0.069162  0.952291  0.286542
1  0.995885  0.158381  0.244274  ...  0.232135  0.549324  0.572232
2  0.641917  0.821055  0.392437  ...  0.430411  0.531757  0.489528
3  0.806532  0.569258  0.148175  ...  0.402791  0.685976  0.246594
4  0.311185  0.501165  0.365979  ...  0.229109  0.022881  0.479022

[10 rows x 20 columns]


### 8. Use a list comprehension to select and print the column numbers for columns from the data set whose median is less than 0.48.

In [113]:
pd.DataFrame.describe(combined_csv)


0          1          2  ...         17         18         19
count  50.000000  50.000000  50.000000  ...  50.000000  50.000000  50.000000
mean    0.511222   0.476279   0.498441  ...   0.482214   0.517030   0.536524
std     0.284799   0.266627   0.302337  ...   0.264955   0.309916   0.281517
min     0.033415   0.031410   0.005691  ...   0.033474   0.016787   0.002596
25%     0.266798   0.239987   0.199247  ...   0.273906   0.186165   0.311481
50%     0.518393   0.498298   0.476174  ...   0.473843   0.537067   0.556300
75%     0.733063   0.717636   0.776483  ...   0.685266   0.802180   0.779484
max     0.995885   0.955196   0.959355  ...   0.982256   0.984628   0.968681

[8 rows x 20 columns]

In [120]:
medians_columns = [0.518393, 0.498298, 0.476174, 0.617797, 0.544392, 0.652570, 0.589559, 0.652583, 0.484164, 0.456142, 0.529412, 0.517590, 0.450881, 0.693514, 0.432621, 0.574287, 0.527874, 0.473843, 0.537067, 0.556300]

medians_less =[i for i in medians_columns if i<0.48]

print(medians_less)

[0.476174, 0.456142, 0.450881, 0.432621, 0.473843]


### 9. Use a list comprehension to add a new column (20) to the data frame whose values are the values in column 19 minus 0.1. Display the top 10 rows of the resulting data frame.

In [122]:
matrix = pd.DataFrame.describe(combined_csv)

matrix ["20"] = matrix["19"] - 0.1

pd.DataFrame.describe(matrix)

0          1          2  ...         18         19         20
count   8.000000   8.000000   8.000000  ...   8.000000   8.000000   8.000000
mean    6.667947   6.648179   6.652216  ...   6.669222   6.679573   6.579573
std    17.511305  17.519157  17.517802  ...  17.511105  17.506676  17.506676
min     0.033415   0.031410   0.005691  ...   0.016787   0.002596  -0.097404
25%     0.280299   0.259967   0.276565  ...   0.278978   0.303990   0.203990
50%     0.514808   0.487288   0.487308  ...   0.527048   0.546412   0.446412
75%     0.798769   0.777026   0.822201  ...   0.847792   0.826784   0.726784
max    50.000000  50.000000  50.000000  ...  50.000000  50.000000  49.900000

[8 rows x 21 columns]

### 10. Use a list comprehension to extract and print all values from the data set that are between 0.7 and 0.75.